### ISSUE TITLE
Emptyyyy

### ISSUE THREAD

**Issue by learntrex** [hightrex/simple_blog#1]
ADDD SOMEETHING

**Comment by Miltonbhowmick** [comment]
What do you want to add?

**Comment by hightrex** [comment]
im trying to get how git works
my tags brought you here?

**Comment by CFokstuen** [comment]
"my tags brought you here?", indeed they have :)

You sought assistance with the "help wanted" tag. If there is a project that you require assistance with then the tag is helpful. It assists everyone involved to mention language/tech, and the specifics of the project and where/how You would require assistance.

Good luck in your learning.

**Comment by hightrex** [comment]
thank youu :D
